services:
  - type: web
    name: maavidyalib-backend
    env: docker
    plan: free
    rootDir: backend
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://db.devxjqycgnccoahgvojc.supabase.co:5432/postgres?sslmode=require
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        sync: false
